version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "exclude"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      serde:
        patterns:
          - serde
          - serde_*
          - serde-*
          - toml
      rust:
        patterns:
          - "*"
