version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      serde:
        patterns:
          - serde
          - serde_*
          - serde-*
          - toml
      misc:
        patterns:
          - anyhow
          - thiserror
          - tracing
          - tracing*
          - log
          - env_logger
      clap:
        patterns:
          - clap
          - clap-*
          - clap_*
