on:
  pull_request:
  push:
    branches:
      - try/**
    tags-ignore:
      - v*.*.*
      - '[0-9]+.[0-9]+.[0-9]+'


name: Checks & Tests

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check-and-test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - windows
          - macos
        toolchain:
          - stable
          - 1.70.0

    name: Test on ${{ matrix.platform }} with ${{ matrix.toolchain }}
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Configure toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update -c clippy
          rustup default ${{ matrix.toolchain }}

      - name: Check
        run: cargo check

      -  run: cargo install --debug --path .
      #- run: cargo test ||
      - run: jq --help || true
      - run: yq '.[2].metadata' < test/deploy.yaml || true
      - run: yq '.[2].metadata' -c < test/deploy.yaml || true
      - run: RUST_LOG=debug cargo test -- --nocapture || true

      - name: Test
        run: just test

      - name: Clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy

  check-only:
    strategy:
      matrix:
        target:
          - x86_64-unknown-freebsd
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
        include:
          - target: x86_64-unknown-freebsd
            platform: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: aarch64-pc-windows-msvc
            platform: windows-latest

    name: Check only for ${{ matrix.target }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          rustup toolchain install stable --profile minimal --no-self-update --target ${{ matrix.target }}
          rustup default stable
      - name: Check
        run: cargo check --target ${{ matrix.target }}
